import { Meteor } from 'meteor/meteor'

import './methods/validate'
import './methods/genURL'
import './methods/getInstances'
import './methods/nextInstances'
import './methods/getProjection'
import './methods/shareInstance'
import './methods/getModel'
import './methods/getStats'
import './methods/downloadTree'
import './methods/navInstance'

import './publications/modelFromLink'
import './publications/statsFromLink'
