version: '3'
services:
  meteor:
    build:
      context: ./meteor/
    ports:
      - "3000:3000"
    links:
      - mongo
      - api
    volumes:
       - ./task_jsons:/usr/src/app/private/
    environment:
      - MONGO_URL=mongodb://mongo:27017/meteor
    platform: linux/amd64
  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    ports:
      - "27017:27017"
  api:
    build:
      context: ./api/
    expose: 
      - "4001"
